"""
page_doctor.py

⭐ Portfolio Doctor page.

Diagnoses portfolio problems and writes prescriptions — like a doctor.

    Portfolio Diagnosis
    ───────────────────
    Problem   : Too much Banking
    Impact    : High Risk
    Suggested Fix:
        Sell 5%  ICICIBANK
        Buy  5%  LT

No jargon. No raw numbers. Just clear recommendations.

Version : 11.0.1
"""

from __future__ import annotations

import streamlit as st

from qpip.portfolio_doctor import PortfolioDoctor
from qpip.risk_engine      import _SECTOR_MAP


_IMPACT_EMOJI = {
    "High Risk"       : "🔴",
    "Moderate Risk"   : "🟡",
    "Opportunity Cost": "🔵",
}


def render(results: dict):
    signals_map = results.get("signals_map", {})
    weights     = results.get("weights", {})

    st.markdown(
        "<h2 style='font-size:22px;font-weight:800;margin-bottom:4px;'>"
        "⭐ Portfolio Doctor</h2>",
        unsafe_allow_html=True,
    )
    st.caption(
        "Your portfolio, diagnosed and prescribed — "
        "like a doctor writing a treatment plan."
    )
    st.divider()

    if not signals_map:
        st.info("Run analysis from the sidebar to get a portfolio diagnosis.")
        return

    doctor = PortfolioDoctor(signals_map, weights if weights else None)
    report = doctor.diagnose()

    if report.clean_bill:
        st.markdown(
            f"<div style='background:#dcfce7;border:2px solid #16a34a;"
            f"border-radius:12px;padding:24px;text-align:center;'>"
            f"<div style='font-size:40px;'>✅</div>"
            f"<div style='font-size:20px;font-weight:800;color:#16a34a;"
            f"margin-top:8px;'>Clean Bill of Health</div>"
            f"<div style='font-size:14px;color:#1f2328;margin-top:8px;'>"
            f"{report.clean_message}</div>"
            f"</div>",
            unsafe_allow_html=True,
        )
        return

    # ── Diagnosis cards ───────────────────────────────────────────────
    for i, dx in enumerate(report.diagnoses, 1):
        imp_emoji = _IMPACT_EMOJI.get(dx.impact, "⚠")
        st.markdown(
            f"<div style='border:1px solid #e5e7eb;border-radius:12px;"
            f"padding:20px 24px;margin-bottom:16px;background:#fff;"
            f"border-left:4px solid {dx.impact_color};'>"
            f"<div style='display:flex;align-items:flex-start;gap:16px;'>"
            f"<div style='font-size:32px;'>{imp_emoji}</div>"
            f"<div style='flex:1;'>"
            f"<div style='font-size:11px;font-weight:700;text-transform:uppercase;"
            f"letter-spacing:.08em;color:#57606a;'>Diagnosis #{i}</div>"
            f"<div style='font-size:18px;font-weight:800;margin:4px 0;'>"
            f"{dx.problem}</div>"
            f"<div style='font-size:13px;color:{dx.impact_color};"
            f"font-weight:700;margin-bottom:10px;'>"
            f"Impact: {dx.impact}</div>"
            f"<div style='background:#f7f8fa;border-radius:8px;padding:12px 16px;"
            f"border:1px solid #e5e7eb;'>"
            f"<div style='font-size:11px;font-weight:700;text-transform:uppercase;"
            f"letter-spacing:.08em;color:#57606a;margin-bottom:6px;'>Prescription</div>"
            f"<div style='font-size:14px;font-weight:700;margin-bottom:4px;'>"
            f"💊 {dx.fix_action} {dx.fix_pct} <span style='color:#2563eb;'>"
            f"{dx.fix_symbol}</span></div>"
            f"<div style='font-size:13px;color:#57606a;'>{dx.fix_detail}</div>"
            f"</div>"
            f"</div>"
            f"</div>"
            f"</div>",
            unsafe_allow_html=True,
        )

    # ── Summary prescription note ─────────────────────────────────────
    st.divider()
    st.markdown(
        "<div style='background:#eff6ff;border-radius:10px;padding:14px 18px;"
        "font-size:13px;color:#1d4ed8;'>"
        "💡 <strong>Note:</strong> These recommendations are generated by the "
        "quantum intelligence engine based on current market signals and "
        "portfolio composition. Always consult a financial advisor before "
        "making significant portfolio changes."
        "</div>",
        unsafe_allow_html=True,
    )
